### ISSUE TITLE
yolov5配置文件夹里全是空的

### ISSUE THREAD

**Issue by shenhaibb** [jolly-xw/11111#1]
yolov5配置文件夹里全是空的

**Comment by shenhaibb** [comment]
其他很多代码也都是空的

**Comment by jolly-xw** [comment]
不好意思 我几天就解决一下 抱歉了



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年01月14日 22:03 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | Re: [jolly-xw/mmdetection-yolov5] yolov5配置文件夹里全是空的 (Issue #1) |

其他很多代码也都是空的

**Comment by jolly-xw** [comment]
新上传的 https://github.com/jolly-xw/mmdetection-yolov5

**Comment by jolly-xw** [comment]
> 

https://github.com/jolly-xw/mmdetection-yolov5

**Comment by shenhaibb** [comment]
谢谢大佬
